//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZicoxPrinter.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ZicoxPrinter.Properties.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 CPCL ruler 的本地化字符串。
        /// </summary>
        public static string CPCL尺子 {
            get {
                return ResourceManager.GetString("CPCL尺子", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hello World 的本地化字符串。
        /// </summary>
        public static string HelloWorld {
            get {
                return ResourceManager.GetString("HelloWorld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SDK initialization failed 的本地化字符串。
        /// </summary>
        public static string SDK初始化失败 {
            get {
                return ResourceManager.GetString("SDK初始化失败", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Download completed 的本地化字符串。
        /// </summary>
        public static string 下载完成 {
            get {
                return ResourceManager.GetString("下载完成", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Download 的本地化字符串。
        /// </summary>
        public static string 下载更新 {
            get {
                return ResourceManager.GetString("下载更新", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Download update failure 的本地化字符串。
        /// </summary>
        public static string 下载更新失败 {
            get {
                return ResourceManager.GetString("下载更新失败", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ready to download and update failed 的本地化字符串。
        /// </summary>
        public static string 准备下载更新失败 {
            get {
                return ResourceManager.GetString("准备下载更新失败", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Initialized Bluetooth module failed 的本地化字符串。
        /// </summary>
        public static string 初始化蓝牙模块失败 {
            get {
                return ResourceManager.GetString("初始化蓝牙模块失败", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Refresh 的本地化字符串。
        /// </summary>
        public static string 刷新 {
            get {
                return ResourceManager.GetString("刷新", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Load CPCL example 的本地化字符串。
        /// </summary>
        public static string 加载CPCL示例 {
            get {
                return ResourceManager.GetString("加载CPCL示例", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Found new version 的本地化字符串。
        /// </summary>
        public static string 发现新版本 {
            get {
                return ResourceManager.GetString("发现新版本", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Send Command 的本地化字符串。
        /// </summary>
        public static string 发送指令 {
            get {
                return ResourceManager.GetString("发送指令", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        public static string 取消 {
            get {
                return ResourceManager.GetString("取消", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No 的本地化字符串。
        /// </summary>
        public static string 否 {
            get {
                return ResourceManager.GetString("否", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Picture width 的本地化字符串。
        /// </summary>
        public static string 图片宽度 {
            get {
                return ResourceManager.GetString("图片宽度", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Picture height 的本地化字符串。
        /// </summary>
        public static string 图片高度 {
            get {
                return ResourceManager.GetString("图片高度", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add new print parameters 的本地化字符串。
        /// </summary>
        public static string 增加新的打印参数 {
            get {
                return ResourceManager.GetString("增加新的打印参数", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Install 的本地化字符串。
        /// </summary>
        public static string 安装更新 {
            get {
                return ResourceManager.GetString("安装更新", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Installation and update failed 的本地化字符串。
        /// </summary>
        public static string 安装更新失败 {
            get {
                return ResourceManager.GetString("安装更新失败", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Try to close Bluetooth 的本地化字符串。
        /// </summary>
        public static string 尝试关闭蓝牙 {
            get {
                return ResourceManager.GetString("尝试关闭蓝牙", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Try to open Bluetooth 的本地化字符串。
        /// </summary>
        public static string 尝试打开蓝牙 {
            get {
                return ResourceManager.GetString("尝试打开蓝牙", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Application theme 的本地化字符串。
        /// </summary>
        public static string 应用主题 {
            get {
                return ResourceManager.GetString("应用主题", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 App 的本地化字符串。
        /// </summary>
        public static string 应用版本 {
            get {
                return ResourceManager.GetString("应用版本", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Current version 的本地化字符串。
        /// </summary>
        public static string 当前版本 {
            get {
                return ResourceManager.GetString("当前版本", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bluetooth is not available for the current device 的本地化字符串。
        /// </summary>
        public static string 当前设备的蓝牙不可用 {
            get {
                return ResourceManager.GetString("当前设备的蓝牙不可用", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ignore the update 的本地化字符串。
        /// </summary>
        public static string 忽略该更新 {
            get {
                return ResourceManager.GetString("忽略该更新", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Print 的本地化字符串。
        /// </summary>
        public static string 打印 {
            get {
                return ResourceManager.GetString("打印", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Print CPCL ruler 的本地化字符串。
        /// </summary>
        public static string 打印CPCL尺子 {
            get {
                return ResourceManager.GetString("打印CPCL尺子", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Print Image 的本地化字符串。
        /// </summary>
        public static string 打印大图 {
            get {
                return ResourceManager.GetString("打印大图", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Print failed 的本地化字符串。
        /// </summary>
        public static string 打印失败 {
            get {
                return ResourceManager.GetString("打印失败", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Print preview 的本地化字符串。
        /// </summary>
        public static string 打印预览 {
            get {
                return ResourceManager.GetString("打印预览", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Print preview width 的本地化字符串。
        /// </summary>
        public static string 打印预览宽度 {
            get {
                return ResourceManager.GetString("打印预览宽度", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Print preview high 的本地化字符串。
        /// </summary>
        public static string 打印预览高度 {
            get {
                return ResourceManager.GetString("打印预览高度", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Scanning ... 的本地化字符串。
        /// </summary>
        public static string 扫描中 {
            get {
                return ResourceManager.GetString("扫描中", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Scanning Bluetooth equipment 的本地化字符串。
        /// </summary>
        public static string 扫描蓝牙设备 {
            get {
                return ResourceManager.GetString("扫描蓝牙设备", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 hint 的本地化字符串。
        /// </summary>
        public static string 提示 {
            get {
                return ResourceManager.GetString("提示", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File size 的本地化字符串。
        /// </summary>
        public static string 文件大小 {
            get {
                return ResourceManager.GetString("文件大小", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New parameter 的本地化字符串。
        /// </summary>
        public static string 新增参数 {
            get {
                return ResourceManager.GetString("新增参数", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Can&apos;t print, the printer cover is opened! 的本地化字符串。
        /// </summary>
        public static string 无法打印打印机开盖 {
            get {
                return ResourceManager.GetString("无法打印打印机开盖", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Can&apos;t print, printers are short of paper! 的本地化字符串。
        /// </summary>
        public static string 无法打印打印机缺纸 {
            get {
                return ResourceManager.GetString("无法打印打印机缺纸", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Yes 的本地化字符串。
        /// </summary>
        public static string 是 {
            get {
                return ResourceManager.GetString("是", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No update 的本地化字符串。
        /// </summary>
        public static string 暂不更新 {
            get {
                return ResourceManager.GetString("暂不更新", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Update download failed 的本地化字符串。
        /// </summary>
        public static string 更新下载失败 {
            get {
                return ResourceManager.GetString("更新下载失败", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Change log 的本地化字符串。
        /// </summary>
        public static string 更新日志 {
            get {
                return ResourceManager.GetString("更新日志", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Latest version 的本地化字符串。
        /// </summary>
        public static string 最新版本 {
            get {
                return ResourceManager.GetString("最新版本", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Check for updates 的本地化字符串。
        /// </summary>
        public static string 检查更新 {
            get {
                return ResourceManager.GetString("检查更新", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Check the update failure 的本地化字符串。
        /// </summary>
        public static string 检查更新失败 {
            get {
                return ResourceManager.GetString("检查更新失败", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Is bluetooth available 的本地化字符串。
        /// </summary>
        public static string 检查蓝牙是否可用 {
            get {
                return ResourceManager.GetString("检查蓝牙是否可用", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bluetooth state 的本地化字符串。
        /// </summary>
        public static string 检查蓝牙是否开启 {
            get {
                return ResourceManager.GetString("检查蓝牙是否开启", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Downloading 的本地化字符串。
        /// </summary>
        public static string 正在下载更新 {
            get {
                return ResourceManager.GetString("正在下载更新", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No equipment 的本地化字符串。
        /// </summary>
        public static string 没有可用的设备 {
            get {
                return ResourceManager.GetString("没有可用的设备", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No effective print parameters 的本地化字符串。
        /// </summary>
        public static string 没有有效的打印参数 {
            get {
                return ResourceManager.GetString("没有有效的打印参数", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to generate thumbnail 的本地化字符串。
        /// </summary>
        public static string 生成缩略图失败 {
            get {
                return ResourceManager.GetString("生成缩略图失败", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to generate preview 的本地化字符串。
        /// </summary>
        public static string 生成预览图失败 {
            get {
                return ResourceManager.GetString("生成预览图失败", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OK to remove this parameter 的本地化字符串。
        /// </summary>
        public static string 确定移除该参数 {
            get {
                return ResourceManager.GetString("确定移除该参数", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove 的本地化字符串。
        /// </summary>
        public static string 移除 {
            get {
                return ResourceManager.GetString("移除", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Update immediately 的本地化字符串。
        /// </summary>
        public static string 立即更新 {
            get {
                return ResourceManager.GetString("立即更新", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Print CPCL 的本地化字符串。
        /// </summary>
        public static string 自定义CPCL指令 {
            get {
                return ResourceManager.GetString("自定义CPCL指令", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Print More 的本地化字符串。
        /// </summary>
        public static string 自定义打印参数 {
            get {
                return ResourceManager.GetString("自定义打印参数", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Adaptive high and width 的本地化字符串。
        /// </summary>
        public static string 自适应高宽 {
            get {
                return ResourceManager.GetString("自适应高宽", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Get Bluetooth paired devices 的本地化字符串。
        /// </summary>
        public static string 获取配对设备 {
            get {
                return ResourceManager.GetString("获取配对设备", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bluetooth 的本地化字符串。
        /// </summary>
        public static string 蓝牙 {
            get {
                return ResourceManager.GetString("蓝牙", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bluetooth unavailable 的本地化字符串。
        /// </summary>
        public static string 蓝牙不可用 {
            get {
                return ResourceManager.GetString("蓝牙不可用", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bluetooth closure 的本地化字符串。
        /// </summary>
        public static string 蓝牙关闭 {
            get {
                return ResourceManager.GetString("蓝牙关闭", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bluetooth available 的本地化字符串。
        /// </summary>
        public static string 蓝牙可用 {
            get {
                return ResourceManager.GetString("蓝牙可用", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bluetooth opening 的本地化字符串。
        /// </summary>
        public static string 蓝牙开启 {
            get {
                return ResourceManager.GetString("蓝牙开启", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bluetooth printer connection fails 的本地化字符串。
        /// </summary>
        public static string 蓝牙打印机连接失败 {
            get {
                return ResourceManager.GetString("蓝牙打印机连接失败", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Settings 的本地化字符串。
        /// </summary>
        public static string 设置 {
            get {
                return ResourceManager.GetString("设置", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please select pictures 的本地化字符串。
        /// </summary>
        public static string 请选择图片 {
            get {
                return ResourceManager.GetString("请选择图片", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please select the device 的本地化字符串。
        /// </summary>
        public static string 请选择设备 {
            get {
                return ResourceManager.GetString("请选择设备", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Follow the system 的本地化字符串。
        /// </summary>
        public static string 跟随系统 {
            get {
                return ResourceManager.GetString("跟随系统", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select Image 的本地化字符串。
        /// </summary>
        public static string 选择图片 {
            get {
                return ResourceManager.GetString("选择图片", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Choose a printer 的本地化字符串。
        /// </summary>
        public static string 选择打印机 {
            get {
                return ResourceManager.GetString("选择打印机", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pair 的本地化字符串。
        /// </summary>
        public static string 配对 {
            get {
                return ResourceManager.GetString("配对", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error 的本地化字符串。
        /// </summary>
        public static string 错误 {
            get {
                return ResourceManager.GetString("错误", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Page width 的本地化字符串。
        /// </summary>
        public static string 页宽 {
            get {
                return ResourceManager.GetString("页宽", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Page high 的本地化字符串。
        /// </summary>
        public static string 页高 {
            get {
                return ResourceManager.GetString("页高", resourceCulture);
            }
        }
    }
}
